# Generated by Django 4.1.3 on 2022-12-02 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=80, verbose_name='Nombres')),
                ('apellido1', models.CharField(max_length=80, verbose_name='Apellido Paterno')),
                ('apellido2', models.CharField(max_length=80, verbose_name='Apellido Materno')),
                ('fechanacimiento', models.DateField(verbose_name='Fecha Nacimiento')),
                ('genero', models.IntegerField(choices=[(0, 'Sin genero'), (1, 'Femenino'), (2, 'Masculino')], verbose_name='Genero')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
            },
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
    ]
